[project]
name = "kstd"
version = "0.1.0"
entry = "src/kstd.kly"

[build]
compiler = "../kelyra/build/bin/kelyra"
kind = "library"
optimization = 0
safe-level = 1
c-sources = ["src/std/io.c", "src/std/alloc.c", "src/std/string.c"]
c-args = []

[package]
output = "kstd-0.1.0.tar.gz"

[test]
sources = ["src/ascii_example.kly", "src/io_example.kly", "src/math_example.kly", "src/string_example.kly"]
